app = "inbound-carrier-sales-one"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  DB_PATH = "/data/data.db"
  SEED_PATH = "/app/app/seed.sql"
  UVICORN_WORKERS = "2"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health"

# attach the SQLite volume at /data
[[mounts]]
  source = "data"
  destination = "/data"
